Updating repository
grupoflux/RFID_Reader pull request #6
Opened 2018-10-18 21:44 UTC by Gustavobelfort

Adding the first functional version uniting the RFID and the POST requests

2018-10-18 22:52 UTC, asf89 requested changes
Deixa apenas as linhas 45 e 51 comentadas, para a gente não perder o código hexadecimal do cartão e do token. O restante pode apagar.

2018-10-18 23:13 UTC, Gustavobelfort commented
Mas não precisa mais, o código já está funcionando

2018-10-18 23:15 UTC, Gustavobelfort commented
Não sei se é necessário deixar essas linhas antigas, qualquer coisa a gente pode olhar no histórico do repositório

2018-10-19 10:47 UTC, Snakedark commented
Certo, então.

2018-10-19 10:47 UTC, asf89 approved these changes

2018-10-19 11:12 UTC, merged